### ISSUE TITLE
Fix for `ERR_OSSL_EVP_UNSUPPORTED` after `npm start`

### ISSUE THREAD

**Issue by JulianCataldo** [tomoyanonymous/nannou-web-template#1]
Hey! Thanks a lot for this starter template.

Had this problem running `npm start`, macOS 12.5, M1 chip, Node 18.

The gist of the error is:
```
ERR_OSSL_EVP_UNSUPPORTED

node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
```

Here is the **fix**:

`export NODE_OPTIONS=--openssl-legacy-provider`

Source : https://stackoverflow.com/a/69746937/2890472

**Comment by tomoyanonymous** [comment]
Thanks for reporting.  I'm on Node v18.9.0, macOS 12.3.1, MacBook Pro 16inch 2019(Intel) but I don't see the problem.

But adding option `output.hashFunction: "xxhash64"` for webpack can also fix this issue, so I'll make the PR.
https://github.com/webpack/webpack/issues/14532#issuecomment-947525539

(Anyway the original template for wasm-pack was a bit out of date(Webpack was 4.x.x).
